### ISSUE TITLE
Industrial Furnace now working.

### ISSUE THREAD

**Issue by Furious1964** [RafalBerezin/Sixty_Four_Mods#1]
Can seem to get this mod to work. Have the .js file in the mods folder and the /img folder there as well, but nothing happens when I place the Ozidizer down. Does this not work anymore?

**Comment by RafalBerezin** [comment]
It still works, but the new machine is unlocked later after placing a Celestial Reactor. I just added the information to the description. Sorry for the misunderstanding.

**Comment by Furious1964** [comment]
Thanks, man. Do you happen to know at which depth level the various gems are accessed? Can't seem to get more of the 6th gem.
